services:
  app:
    image: front:latest
    container_name: front_test
    ports:
      - '3000:3000'
    environment:
      API_URL: http://app:80
    networks:
      - artichaut-net

networks:
  artichaut-net:
    external: true